namespace Domain.Entities;

public class GamingBuilds : BaseEntity
{
    public string Case { get; set; } = string.Empty;
    // 2E gaming, Bloody ....
    public string CPU { get; set; } = string.Empty;
    // Intel , AMD .......
    public string MB { get; set; } = string.Empty;
    // Asus  .........
    public string Cooler { get; set; } = string.Empty;
    // A100, DeepCool .....
    public string RAM { get; set; } = string.Empty;
    // DDR4, DDR 5
    public string HDD { get; set; } = string.Empty;
    public string GPU { get; set; } = string.Empty;
    // GTX, RTX ......
    public string PSU { get; set; } = string.Empty;
    // DeepColl .............
    public string SSD { get; set; } = string.Empty;
    // NVMe 516 .......
}
